# Values for chart for the main dev instance of Workbench
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
  # Where should we send the user to log in?
  signInUrl: "https://dev.ndslabs.org/oauth2/start"

  # How to know if we should route to the login page
  privateAuth:
    forwardAddress: "https://dev.ndslabs.org/oauth2/auth"

# How should this error page be served?
ingress:
  hostname: "dev.ndslabs.org"
  
