{{- if .Values.customErrors }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.customErrorsName }}
spec:
  ingressClassName: '{{ index .Values "oauth2-proxy" "ingress" "ingressClassName" }}'
  tls:
    - hosts:
      - '{{ index .Values "oauth2-proxy" "ingress" "hostname" }}'
      secretName: ndslabs-tls
  rules:
  - host: '{{ index .Values "oauth2-proxy" "ingress" "hostname" }}'
    http:
      paths:
      - path: /401.html
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.customErrorsName }}
            port:
              number: 80
      - path: /env.js
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.customErrorsName }}
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.customErrorsName }}
spec:
  selector:
    app: {{ .Values.customErrorsName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.customErrorsName }}
  labels:
    app: {{ .Values.customErrorsName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.customErrorsName }}
  template:
    metadata:
      labels:
        app: {{ .Values.customErrorsName }}
    spec:
      containers:
      - name: nginx
        image: moleculemaker/custom-errors
        imagePullPolicy: Always
        env:
          - name: SIGN_IN_URL
            value: {{ .Values.customErrorsSignInUrl }}
        ports:
        - containerPort: 80
{{- end }}
